### ISSUE TITLE
feat: Don't auto-dismiss the playback toolbar when the cursor is over it, also make it possible to click anywhere to progress

### ISSUE THREAD

**Issue by matthew-carroll** [mkobuolys/flutter_deck#111]
I'm doing run throughs of a presentation. I place the cursor over the "next" button to click through some slides. But when I take more than a few seconds on a given slide, the control bar disappears, even while the cursor remains of the "next" button.

The reason that I'm trying to leave the cursor over the next button is because I'm used to clicking anywhere to move forward. I was hoping that I could leave the cursor on the "next" button to still accomplish that. But it disappears.

Along those lines, I'd like the ability to enable a "click anywhere to move forward" mode. I'm guessing that this can be implemented by disabling standard controls and then adding appropriate gesture detectors to all slides. But that's a very significant modification to gain a standard slideshow control mechanism.

**Comment by mkobuolys** [comment]
Could you let me know why you're not using keyboard shortcuts? There are several reasons why controls were implemented this way:
1. Usually, slideshows support both - "click anywhere to move forward" and arrow keys - navigation types to control the slideshow. Remember, one of the main points of using flutter_deck is to have interactivity inside slides. I am afraid that using mouse clicks for controls could lead to some unwanted side effects.
2. I checked multiple remote presentation clickers before implementing flutter_deck controls. Usually, the main key to switch the slide is mapped to an arrow key, and not a mouse click. This way, by using keyboard shortcuts, presentation clickers work out of the box, too.

**Comment by matthew-carroll** [comment]
> Could you let me know why you're not using keyboard shortcuts?

I was just used to using my mouse.

As you mentioned, most slideshows support clickthrough. 

Supporting clickthrough doesn't need to get in the way of other interactivity (the gesture recognizer can be placed beneath all the content to defer to all other recognizers), and while I think it should be the default, it can also be implemented in a way that would allow you to turn it off.
