### ISSUE TITLE
refactor: Improve code highlight

### ISSUE THREAD

**Issue by lucas-goldner** [mkobuolys/flutter_deck#113]
**Description**

Having worked on two presentations with flutter_deck, I am enjoying it, but one thing I think could be improved: Showing code.

## Design:

Here are two screenshots comparing how it looks on flutter_deck and how I implemented it in fluttershow:

flutter_deck
<img width="835" alt="image" src="https://github.com/user-attachments/assets/27edb26f-3bb6-4533-9761-18513163611d">

fluttershow
<img width="621" alt="image" src="https://github.com/user-attachments/assets/f22d5850-2a98-4d51-a3e1-b45eb64d02cf">

You can check the implementation here:
https://github.com/lucas-goldner/fluttershow_base/blob/main/lib/components/widgets/wrapper/code_display.dart

I also have like a billion themes hard coded:
https://github.com/lucas-goldner/fluttershow_base/blob/main/lib/components/model/enum/code_display_themes.dart

Maybe we could merge them somehow for a more appealing view

## Auto format:

This would only work for Dart, but manually formatting can be annoying. 
I used this library here:
https://github.com/lucas-goldner/fluttershow_base/blob/main/lib/components/helper/format_code.dart
Of course, it should be toggleable

**Requirements**

If you agree with any of those points, we can define requirements

**Comment by mkobuolys** [comment]
Hey! I think this issue can be closed and the discussion moved to https://github.com/mkobuolys/flutter_deck/issues/94. Using the same code styling as used in the slick_slides package should also solve this.

**Comment by lucas-goldner** [comment]
Ah didn't see that one, yeah then let's use the slick one 😆
