### ISSUE TITLE
fix: Mobile does not show controls

### ISSUE THREAD

**Issue by rodydavis** [mkobuolys/flutter_deck#118]
**Description**

When running on mobile the controls do not present (event though `presenterToolbarVisible` is true).

On desktop it shows after a mouse hover.

**Expected Behavior**

1. Navigation presentation with gestures and tap to show tool bar
2. Tool bar should be present by default on mobile

**Comment by mkobuolys** [comment]
Hi @rodydavis, could you clarify this? Are you running the slide deck as an Android/iOS app, or are you running a web version on a mobile device? For instance, when I open https://kazlauskas.dev/ldd on my mobile browser, everything functions correctly (as “Navigation presentation with gestures and tap to show tool bar”).

**Comment by rodydavis** [comment]
I am running on Android, iOS, MacOS, Windows and Web.

Only on iOS will the controls not show up and not sure why. Android shows after a tab and desktop after mouse hover.

**Comment by mkobuolys** [comment]
@rodydavis Strange, when I prepare for conferences and want to rehearse the talk on the go, I always open my deployed presentation on the Web using iOS Safari. Controls always show up after a tap on the screen. Just to make sure that's not something with the specifics of your presentation, do you experience the same behaviour with the demo presentation (https://flutterdeck.dev/demo)?

**Comment by rodydavis** [comment]
Web safari works! iOS native does not

**Comment by mkobuolys** [comment]
@rodydavis Oh, ok 😄 I think I've never tried running flutter_deck on iOS/Android as a platform (these are not officially supported, as specified in pub.dev). Still, curious why Android works and iOS does not. Let's keep the issue open, I need to double-check.

**Comment by rodydavis** [comment]
I might also add a PR too, but I am very interested as a big user base of mine is on tablets and mobile.

Specifically preview the presentation on mobile and editing on desktop and web. In my app users export pptx on all platforms locally and I use this package to preview the presentation (I had a custom solution before but nice that this exists now).

**Comment by mkobuolys** [comment]
@rodydavis interesting! I always saw it as desktop-first, meaning, you build the presentation on Desktop and only use it as read-only on mobile (hence the Web to mobile browser flow). Your use case gives a bit of a shift to this, cool to know that.

**Comment by rodydavis** [comment]
Yep that is the idea! Desktop and web are a lot easier for editing presentations, but mobile they can quickly preview before exporting from the app.

The abstraction for the presentation is a list view with structured types so easy to compose cross platform. But previewing is visual to make sure the text and images show up correctly!

**Comment by rodydavis** [comment]
Honestly all I need for mobile is the controls to show by default and tap to dismiss/show instead of hover

**Comment by mkobuolys** [comment]
@rodydavis you can try out the code from the PR in your project now. Let me know if everything works as expected.

**Comment by rodydavis** [comment]
PR works for me! Appeared right after a tap as expected

**Comment by mkobuolys** [comment]
@rodydavis FYI: Released with v0.18.0.
