### ISSUE TITLE
feat: add "quote" slide template

### ISSUE THREAD

**Issue by mkobuolys** [mkobuolys/flutter_deck#22]
**Description**

Add a new "quote" slide template. Example from Keynote:

<img width="865" alt="Screenshot 2023-09-29 at 23 42 59" src="https://github.com/mkobuolys/flutter_deck/assets/17415795/52998745-daad-48be-96be-d75a211835b0">

This template should support a quote (quote text or title) and the author of a quote (smaller text below). Text styles should be applied from a dedicated slide theme.

Also, make sure that the template supports the footer and header based on the slide deck configuration values, and custom background (see existing templates for reference).

**Requirements**

- [ ] Implement a new slide template
- [ ] Implement a new theme for the template
- [ ] Add documentation where needed
- [ ] Update the example app with the new slide template example
- [ ] Update the README.md file with the new slide template example 
- [ ] Prepare the CHANGELOG.md file for an upcoming release

**Comment by notpritam** [comment]
can you assign this to me..

**Comment by mkobuolys** [comment]
Sure, good luck!

**Comment by mkobuolys** [comment]
@notpritam Feel free to use https://github.com/mkobuolys/flutter_deck/issues/21 for reference to make the collaboration more efficient.

**Comment by notpritam** [comment]
> @notpritam Feel free to check #24 for reference to make the collaboration more efficient.

Okay got it , thanks for the reference...

**Comment by mkobuolys** [comment]
@notpritam Any progress or we can re-open this issue for someone else?

**Comment by notpritam** [comment]
> @notpritam Any progress or we can re-open this issue for someone else?

I am almost done, i am pushing it in few hours

**Comment by mkobuolys** [comment]
> > @notpritam Any progress or we can re-open this issue for someone else?
> 
> I am almost done, i am pushing it in few hours

I am sorry for being pushy, but I do not even see that you have forked the repository - is it really a matter of hours?

**Comment by priyavratamohan** [comment]
Hi @mkobuolys, could you assign this issue to me?

**Comment by mkobuolys** [comment]
> Hi @mkobuolys, could you assign this issue to me?

Let's wait for the @notpritam response/progress change until tomorrow. If there is none, I will re-assign the issue to you since the Hacktoberfest is going to end soon  👍

**Comment by mkobuolys** [comment]
Ok @priyavratamohan, assigning this to you - good luck!

**Comment by mkobuolys** [comment]
@priyavratamohan A friendly reminder that Hacktoberfest is coming to an end.

**Comment by mkobuolys** [comment]
Implemented with https://github.com/mkobuolys/flutter_deck/pull/37
