### ISSUE TITLE
test: add Widget tests for slide templates

### ISSUE THREAD

**Issue by mkobuolys** [mkobuolys/flutter_deck#23]
**Description**

Add widget tests for the available slide templates. These tests should check whether the defined slide elements are visible. Also, they should test different slide configuration values (e.g. header and footer visible, custom background set, etc.).

**Requirements**

- [ ] There is no drop in test coverage.

**Comment by bryanoli** [comment]
Hello! I would like to work on this issue.

**Comment by mkobuolys** [comment]
Hey, sure, enjoy! 🤓

**Comment by mkobuolys** [comment]
@bryanoli I cannot find you on any social media. Could you reach out to me on X or LinkedIn so that we can arrange the delivery of your prize?

**Comment by bryanoli** [comment]
Hey @mkobuolys. My social on LinkedIn is https://www.linkedin.com/in/bryanoli/
I cannot message you directly due to not having premium subscription.
