### ISSUE TITLE
fix: Controls break after full screen on macOS

### ISSUE THREAD

**Issue by dumazy** [mkobuolys/flutter_deck#25]
**Description**

The controls no longer work when the app has gone to full screen on macOS. After closing full screen, they still don't work. 
I'm using `flutter_deck: 0.5.0`

**Steps To Reproduce**

1. Create an example with 2 slides
2. Run app on macOS in debug mode
3. Verify that the default controls (left & right keys) are working
4. Open the app window full screen (green window button or `fn + F`)
5. The controls no longer work
6. Close the full screen mode again
7. The controls still don't work

**Expected Behavior**

The controls should work when putting the app full screen and continue to work after closing the full screen mode

**flutter doctor output**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-BE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

The example app in on the `main` branch has a similar issue, but there it only occurs after closing full screen mode and only when closing with the escape key

1. Run example app
2. Verify that the controls are working
3. Open the app window full screen
4. The controls are still working => wasn't the case with my own example app
5. Close full screen mode **with the escape key**
6. The controls are no longer working
7. Open full screen mode again
8. The controls are still not working

**Comment by dumazy** [comment]
The focus tree seems to change depending on whether you are using the ESC key to exit full screen or whether you just click the green window button on macOS.

I've just been doing some (dirty) debugging by dumping the focus tree when `ShortcutManager.handleKeypress` is called, using `debugDumpFocusTree()`. Apparently, if you put a breakpoint (in VS Code) on that, it will go into an endless loop and keep calling `handleKeyPress` so I had to go with printing to the debug console to figure stuff out. This might be another issue with Flutter itself.

Before exiting with ESC, these are the last parts of the focus tree:
```
flutter:                    └─Child 1: _FocusTraversalGroupNode#4ca4f(FocusTraversalGroup [IN FOCUS PATH])
flutter:                      │ context: Focus
flutter:                      │ NOT FOCUSABLE
flutter:                      │ IN FOCUS PATH
flutter:                      │
flutter:                      └─Child 1: FocusNode#6be53(Navigator [IN FOCUS PATH])
flutter:                        │ context: Focus
flutter:                        │ IN FOCUS PATH
flutter:                        │
flutter:                        ├─Child 1: FocusScopeNode#53a51(_ModalScopeState<dynamic> Focus Scope)
flutter:                        │   context: FocusScope
flutter:                        │
flutter:                        └─Child 2: FocusScopeNode#d29df(_ModalScopeState<dynamic> Focus Scope [PRIMARY FOCUS])
flutter:                            context: FocusScope
flutter:                            PRIMARY FOCUS
```

after exiting with ESC:
```
flutter:                    └─Child 1: _FocusTraversalGroupNode#4ca4f(FocusTraversalGroup [IN FOCUS PATH])
flutter:                      │ context: Focus
flutter:                      │ NOT FOCUSABLE
flutter:                      │ IN FOCUS PATH
flutter:                      │
flutter:                      └─Child 1: FocusNode#6be53(Navigator [IN FOCUS PATH])
flutter:                        │ context: Focus
flutter:                        │ IN FOCUS PATH
flutter:                        │
flutter:                        └─Child 1: FocusScopeNode#d29df(_ModalScopeState<dynamic> Focus Scope [PRIMARY FOCUS])
flutter:                            context: FocusScope
flutter:                            PRIMARY FOCUS
```
"Child 2" seems to be missing, which might contain the `FlutterDeckControl` shortcuts.
I'll see when I can continue to pick this up, but wanted to share the progress on this already.

**Comment by mkobuolys** [comment]
Hey, thanks for the input! I also did some debugging and noticed a similar thing. If you go full-screen using fn + f, the controls stop working, but if you use the green button - all good. Also, what's interesting, is that if you do the following:
1. Go full-screen using fn + f
2. (notice that controls are not working)
3. Press f (without fn)
4. The controls are working again

Having this in mind, I assumed it could be some kind of a focus issue or related to the fn key, but it definitely needs more investigation.

**Comment by dumazy** [comment]
Oh alright, yeah I can reproduce that as well. Even more, after hitting ESC to close the full screen mode, hitting ESC again will allow me to use the controls again 🤔

**Comment by tomcheung** [comment]
If i replace `LogicalKeySet` with `SingleActivator`, it can work property (although it will break logic if you have custom shortcut config using FlutterDeckControlsConfiguration)

https://github.com/mkobuolys/flutter_deck/blob/c313282927ad9c6a8da5433da337de2e6addd2e2/lib/src/controls/flutter_deck_controls_listener.dart#L75-L83

```dart
shortcuts: <ShortcutActivator, Intent>{
  SingleActivator(shortcuts.nextSlide.first): const GoNextIntent(),
  SingleActivator(shortcuts.previousSlide.first): const GoPreviousIntent(),
  // ...
}
```

maybe it have some bug inside `LogicalKeySet` when handling the fn key

**Comment by mkobuolys** [comment]
> If i replace `LogicalKeySet` with `SingleActivator`, it can work property (although it will break logic if you have custom shortcut config using FlutterDeckControlsConfiguration)
> 
> https://github.com/mkobuolys/flutter_deck/blob/c313282927ad9c6a8da5433da337de2e6addd2e2/lib/src/controls/flutter_deck_controls_listener.dart#L75-L83
> 
> ```dart
> shortcuts: <ShortcutActivator, Intent>{
>   SingleActivator(shortcuts.nextSlide.first): const GoNextIntent(),
>   SingleActivator(shortcuts.previousSlide.first): const GoPreviousIntent(),
>   // ...
> }
> ```
> 
> maybe it have some bug inside `LogicalKeySet` when handling the fn key

Good one! I will double-check the behaviour of this 👀

**Comment by mkobuolys** [comment]
Fixed with https://github.com/mkobuolys/flutter_deck/pull/58
