### ISSUE TITLE
feat: Allow sharing an AutoSizeGroup between a FlutterDeckBulletList and other Text widgets

### ISSUE THREAD

**Issue by markvideon** [mkobuolys/flutter_deck#89]
**Description**

As a user of flutter_deck, I would like to be able to size some text to be the same size as the contents of the list

**Requirements**

- [ ] Add an optional parameter for an autoSizeGroup to FlutterDeckBulletList's constructor
- [ ] The internal AutoSizeGroup field should use the group provided to the widget, if available. Otherwise initialise a new group as before.

**Additional Context**

Implementation would look something like the following:

```dart

  FlutterDeckBulletList({
    // other parameters omitted
    this.autoSizeGroup,
  }) : assert(items.isNotEmpty, 'You must provide at least one bullet point.');
  
  /// If provided, an external [AutoSizeGroup] that will be used by the items in the list.
  final AutoSizeGroup? autoSizeGroup;

  // ...

  class _FlutterDeckBulletListState extends State<FlutterDeckBulletList> {
    late final _autoSizeGroup =  widget.autoSizeGroup ?? AutoSizeGroup();
  
    // ...
  }

```

**Comment by mkobuolys** [comment]
Thanks for the suggestion! Implemented with https://github.com/mkobuolys/flutter_deck/pull/90.
