### ISSUE TITLE
docs: change slide color

### ISSUE THREAD

**Issue by jxstxn1** [mkobuolys/flutter_deck#9]
**Description**

Currently, it is not documented that you need to overwrite the color argument of a Slide, for example: In the `FlutterDeckSplitSlide`.

**Requirements**

- [ ] Add a section to change the color or add it in a code block in the readme

**Comment by mkobuolys** [comment]
Hey, @jxstxn1. At the moment, I am working on a global theming solution for the slide deck. I would suggest waiting for it to be released with v0.4.0 and then we will see. How does that sound?

**Comment by jxstxn1** [comment]
This sounds very nice!
