### ISSUE TITLE
feat: Support full screen mode on the desktop

### ISSUE THREAD

**Issue by tomaszpolanski** [mkobuolys/flutter_deck#97]
**Description**

On the web, we can put the browser into full-screen mode to hide the window's title bar and only show the presentation's content.
On the desktop, this is impossible as the title bar will always be visible.
My feature suggestion is to allow the desktop to toggle full-screen mode by pressing the F11 key, the same as on the web

**Requirements**

- [ ] Pressing the F11 key toggles full-screen mode on Windows/Linux/macOS

**Additional Context**

On Windows and Linux which I use, there is no easy way to get rid of the title bar without it being implemented into the app
I've implemented this feature in my presentations and it is convenient.
If this is something that would be useful here, I could create a PR for it.

**Comment by mkobuolys** [comment]
Hi, thanks for the feature request. In flutter_deck, the fullscreen controls are managed through this component https://github.com/mkobuolys/flutter_deck/tree/main/packages/flutter_deck/lib/src/controls/fullscreen. At the moment, only Web is supported, hence this could be a very nice addition to the framework. Just I am not sure whether the same approach should be used or it may be easier to implement and use a federated plugin to control fullscreen management on different platforms.

**Comment by tomaszpolanski** [comment]
I use [WindowManager plugin](https://pub.dev/packages/window_manager)  in my [little project](https://github.com/tomaszpolanski/flutter-presentations/blob/72d7f1454efafbbf57177d3e3e30443c930ddf7f/lib/shared/shortcuts.dart#L54)
It would be easy to use in your `FlutterDeckFullscreenManagerBase`.

The question is if you are ok with using a plugin to have that functionality

**Comment by mkobuolys** [comment]
In this case, it's fine - it does not make sense to re-implement since you will probably end up implementing the same thing all over again.

**Comment by tomaszpolanski** [comment]
Ok, in that case, I will create a PR over the weekend

**Comment by mkobuolys** [comment]
Implemented with https://github.com/mkobuolys/flutter_deck/pull/98
